/**
 * Shared PDF utilities for leave-of-absence and ADA workflows.
 *
 * Builds valid PDF 1.4 documents from plain text using only built-in
 * Type1 fonts (Helvetica / Helvetica-Bold).  No external libraries or
 * font files are required — every PDF reader ships these fonts.
 */

// ---------------------------------------------------------------------------
// Core builder
// ---------------------------------------------------------------------------

export function buildMedCertPdf(content: string, title = "MEDICAL CERTIFICATION FORM"): Buffer {
  const PW = 612, PH = 792, MX = 50, MY = 50;
  const CW = PW - MX * 2;

  function esc(s: string): string {
    return s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
  }

  function approxW(text: string, size: number): number {
    return text.length * size * 0.52;
  }

  function wordWrap(text: string, size: number, maxW: number): string[] {
    if (approxW(text, size) <= maxW) return [text];
    const words = text.split(" ");
    const lines: string[] = [];
    let cur = "";
    for (const word of words) {
      const next = cur ? cur + " " + word : word;
      if (approxW(next, size) <= maxW) { cur = next; }
      else { if (cur) lines.push(cur); cur = word; }
    }
    if (cur) lines.push(cur);
    return lines.length ? lines : [text];
  }

  interface Row { text: string; bold: boolean; sz: number; x: number; lineH: number; }
  const rows: Row[] = [];

  function addRow(text: string, bold: boolean, sz: number, indent = 0, extraSpacing = 0) {
    rows.push({ text, bold, sz, x: MX + indent, lineH: sz + 4 + extraSpacing });
  }

  // Title block
  addRow(title, true, 14, 0, 6);
  addRow("Generated by Guildlight Leave  -  For HR Use Only", false, 9, 0, 10);

  for (const raw of content.split("\n")) {
    const trimmed = raw.trim();
    if (!trimmed) { addRow("", false, 10, 0, 2); continue; }

    const isSectionHeader =
      /^[A-Z][A-Z\s\-]{4,}:?\s*$/.test(trimmed) ||
      /^\d+\.\s+[A-Z]/.test(trimmed);
    const isIndented = raw.startsWith("  ") || raw.startsWith("\t");
    const indent = isIndented ? 20 : 0;

    if (isSectionHeader) {
      addRow("", false, 4, 0, 0);
      for (const wl of wordWrap(trimmed, 10, CW)) addRow(wl, true, 10, 0, 0);
    } else {
      for (const wl of wordWrap(trimmed, 10, CW - indent)) addRow(wl, false, 10, indent, 0);
    }
  }

  // --- Paginate rows ---
  const startY = PH - MY - 18;
  const pages: { row: Row; y: number }[][] = [];
  let curPage: { row: Row; y: number }[] = [];
  let y = startY;

  for (const row of rows) {
    if (y - row.sz < MY + 20 && curPage.length > 0) {
      pages.push(curPage);
      curPage = [];
      y = startY;
    }
    if (row.text) curPage.push({ row, y });
    y -= row.lineH;
  }
  if (curPage.length > 0 || pages.length === 0) pages.push(curPage);

  // --- Build PDF content streams ---
  const streams = pages.map((pg) => {
    const cmds: string[] = ["BT"];
    let curFont = "", curSz = 0;
    for (const { row, y: ry } of pg) {
      const fn = row.bold ? "/F2" : "/F1";
      if (fn !== curFont || row.sz !== curSz) { cmds.push(`${fn} ${row.sz} Tf`); curFont = fn; curSz = row.sz; }
      cmds.push(`1 0 0 1 ${row.x} ${ry.toFixed(1)} Tm`);
      cmds.push(`(${esc(row.text)}) Tj`);
    }
    cmds.push("ET");
    return cmds.join("\n");
  });

  // --- Object ID assignment ---
  const nPages = pages.length;
  const firstPageObj = 3;
  const fontNrm = firstPageObj + nPages;
  const fontBld = fontNrm + 1;
  const firstStream = fontBld + 1;
  const totalObjs = firstStream + nPages;

  // --- Serialize ---
  const parts: string[] = [];
  const offsets: number[] = new Array(totalObjs).fill(0);
  let pos = 0;

  function w(s: string) { parts.push(s); pos += Buffer.byteLength(s, "latin1"); }

  w("%PDF-1.4\n%\xe2\xe3\xcf\xd3\n");

  offsets[1] = pos;
  w(`1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n`);

  const kids = Array.from({ length: nPages }, (_, i) => `${firstPageObj + i} 0 R`).join(" ");
  offsets[2] = pos;
  w(`2 0 obj\n<< /Type /Pages /Kids [${kids}] /Count ${nPages} >>\nendobj\n`);

  for (let i = 0; i < nPages; i++) {
    offsets[firstPageObj + i] = pos;
    w(`${firstPageObj + i} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PW} ${PH}] /Contents ${firstStream + i} 0 R /Resources << /Font << /F1 ${fontNrm} 0 R /F2 ${fontBld} 0 R >> >> >>\nendobj\n`);
  }

  offsets[fontNrm] = pos;
  w(`${fontNrm} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj\n`);

  offsets[fontBld] = pos;
  w(`${fontBld} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>\nendobj\n`);

  for (let i = 0; i < nPages; i++) {
    const stream = streams[i];
    const len = Buffer.byteLength(stream, "latin1");
    offsets[firstStream + i] = pos;
    w(`${firstStream + i} 0 obj\n<< /Length ${len} >>\nstream\n${stream}\nendstream\nendobj\n`);
  }

  const xrefPos = pos;
  w(`xref\n0 ${totalObjs}\n`);
  w(`0000000000 65535 f \n`);
  for (let i = 1; i < totalObjs; i++) {
    w(`${String(offsets[i]).padStart(10, "0")} 00000 n \n`);
  }
  w(`trailer\n<< /Size ${totalObjs} /Root 1 0 R >>\nstartxref\n${xrefPos}\n%%EOF\n`);

  return Buffer.from(parts.join(""), "latin1");
}

// ---------------------------------------------------------------------------
// Format detection helpers
// ---------------------------------------------------------------------------

/**
 * Returns true if `s` is a base64-encoded PDF (starts with the %PDF magic
 * bytes once decoded).  Works for both padded and unpadded base64.
 */
export function isBase64Pdf(s: string): boolean {
  try {
    return Buffer.from(s.slice(0, 20), "base64").slice(0, 4).toString("ascii") === "%PDF";
  } catch {
    return false;
  }
}

/**
 * Accepts either raw text or a base64-encoded PDF string and always returns
 * a valid base64 PDF string suitable for email attachments.
 */
export function toPdfBase64(contentInline: string, title?: string): string {
  if (isBase64Pdf(contentInline)) return contentInline;
  return buildMedCertPdf(contentInline, title).toString("base64");
}

/**
 * Accepts either raw text or a base64-encoded PDF string and always returns
 * a ready-to-send Buffer containing a valid PDF.
 */
export function toPdfBuffer(contentInline: string, title?: string): Buffer {
  if (isBase64Pdf(contentInline)) return Buffer.from(contentInline, "base64");
  return buildMedCertPdf(contentInline, title);
}
