import { Router, type Request, type Response } from "express";
import { eq, and, asc, desc, isNull } from "drizzle-orm";
import {
  db,
  adaCasesTable,
  adaInteractiveLogTable,
  approvedAccommodationsTable,
  calendarInvitesTable,
  organizationsTable,
} from "@workspace/db";
import { requireAuth, type AuthenticatedRequest } from "../lib/jwtAuth.js";
import { logger } from "../lib/logger.js";
import {
  runAdaTurn,
  generatePhysicianCertRequest,
  generateApprovalLetter,
  generateDenialLetter,
  type AdaMessage,
} from "../lib/adaAgent.js";
import { generateIcs } from "../lib/icsGenerator.js";
import { sendNoticeEmail, getAppUrl } from "../lib/email.js";

const router = Router();

/** Pure Node.js PDF generator for ADA documents (same algorithm as buildMedCertPdf in cases.ts) */
function buildSimplePdf(content: string): Buffer {
  const PW = 612, PH = 792, MX = 50, MY = 50;
  const CW = PW - MX * 2;
  function esc(s: string) { return s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)"); }
  function approxW(t: string, sz: number) { return t.length * sz * 0.52; }
  function wordWrap(t: string, sz: number, maxW: number): string[] {
    if (approxW(t, sz) <= maxW) return [t];
    const words = t.split(" "); const lines: string[] = []; let cur = "";
    for (const w of words) { const nx = cur ? cur + " " + w : w; if (approxW(nx, sz) <= maxW) { cur = nx; } else { if (cur) lines.push(cur); cur = w; } }
    if (cur) lines.push(cur); return lines.length ? lines : [t];
  }
  interface Row { text: string; bold: boolean; sz: number; x: number; lineH: number; }
  const rows: Row[] = [];
  function addRow(text: string, bold: boolean, sz: number, indent = 0, extra = 0) { rows.push({ text, bold, sz, x: MX + indent, lineH: sz + 4 + extra }); }
  addRow("ADA PHYSICIAN CERTIFICATION REQUEST", true, 13, 0, 6);
  addRow("Generated by Leavara LeaveIQ  -  For HR Use Only", false, 9, 0, 8);
  for (const raw of content.split("\n")) {
    const trimmed = raw.trim();
    if (!trimmed) { addRow("", false, 10, 0, 2); continue; }
    const isHdr = /^[A-Z\-─]{4,}/.test(trimmed) || /^\d+\.\s+[A-Z]/.test(trimmed);
    const isIndented = raw.startsWith("  ") || raw.startsWith("\t");
    if (isHdr) { addRow("", false, 3, 0, 0); for (const wl of wordWrap(trimmed, 10, CW)) addRow(wl, true, 10, 0, 0); }
    else { for (const wl of wordWrap(trimmed, 10, CW - (isIndented ? 20 : 0))) addRow(wl, false, 10, isIndented ? 20 : 0, 0); }
  }
  const startY = PH - MY - 18; const pages: { row: Row; y: number }[][] = []; let curPage: { row: Row; y: number }[] = []; let y = startY;
  for (const row of rows) { if (y - row.sz < MY + 20 && curPage.length > 0) { pages.push(curPage); curPage = []; y = startY; } if (row.text) curPage.push({ row, y }); y -= row.lineH; }
  if (curPage.length > 0 || pages.length === 0) pages.push(curPage);
  const streams = pages.map(pg => { const cmds = ["BT"]; let cf = "", cs = 0; for (const { row, y: ry } of pg) { const fn = row.bold ? "/F2" : "/F1"; if (fn !== cf || row.sz !== cs) { cmds.push(`${fn} ${row.sz} Tf`); cf = fn; cs = row.sz; } cmds.push(`1 0 0 1 ${row.x} ${ry.toFixed(1)} Tm`); cmds.push(`(${esc(row.text)}) Tj`); } cmds.push("ET"); return cmds.join("\n"); });
  const nP = pages.length, fpO = 3, fnr = fpO + nP, fbd = fnr + 1, fst = fbd + 1, tot = fst + nP;
  const parts: string[] = []; const off: number[] = new Array(tot).fill(0); let pos = 0;
  function w(s: string) { parts.push(s); pos += Buffer.byteLength(s, "latin1"); }
  w("%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"); off[1] = pos; w(`1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n`);
  const kids = Array.from({ length: nP }, (_, i) => `${fpO + i} 0 R`).join(" "); off[2] = pos; w(`2 0 obj\n<< /Type /Pages /Kids [${kids}] /Count ${nP} >>\nendobj\n`);
  for (let i = 0; i < nP; i++) { off[fpO + i] = pos; w(`${fpO + i} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PW} ${PH}] /Contents ${fst + i} 0 R /Resources << /Font << /F1 ${fnr} 0 R /F2 ${fbd} 0 R >> >> >>\nendobj\n`); }
  off[fnr] = pos; w(`${fnr} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj\n`);
  off[fbd] = pos; w(`${fbd} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>\nendobj\n`);
  for (let i = 0; i < nP; i++) { const s = streams[i]; off[fst + i] = pos; w(`${fst + i} 0 obj\n<< /Length ${Buffer.byteLength(s, "latin1")} >>\nstream\n${s}\nendstream\nendobj\n`); }
  const xp = pos; w(`xref\n0 ${tot}\n`); w(`0000000000 65535 f \n`);
  for (let i = 1; i < tot; i++) w(`${String(off[i]).padStart(10, "0")} 00000 n \n`);
  w(`trailer\n<< /Size ${tot} /Root 1 0 R >>\nstartxref\n${xp}\n%%EOF\n`);
  return Buffer.from(parts.join(""), "latin1");
}

function generateCaseNumber(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const rand = Math.floor(Math.random() * 9000) + 1000;
  return `ADA-${year}${month}-${rand}`;
}

// ── ADA Case CRUD ────────────────────────────────────────────────────────────

// GET /api/ada/cases
router.get("/ada/cases", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  try {
    const cases = await db
      .select()
      .from(adaCasesTable)
      .where(and(
        eq(adaCasesTable.organizationId, authed.user.organizationId),
        isNull(adaCasesTable.deletedAt),
      ))
      .orderBy(desc(adaCasesTable.createdAt));
    res.json({ cases });
  } catch (err) {
    logger.error({ err }, "ADA cases list error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// GET /api/ada/cases/:caseId
router.get("/ada/cases/:caseId", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  const { caseId } = req.params;
  try {
    const [adaCase] = await db
      .select()
      .from(adaCasesTable)
      .where(and(eq(adaCasesTable.id, caseId), eq(adaCasesTable.organizationId, authed.user.organizationId)))
      .limit(1);
    if (!adaCase) { res.status(404).json({ error: "Case not found" }); return; }

    const log = await db
      .select()
      .from(adaInteractiveLogTable)
      .where(eq(adaInteractiveLogTable.caseId, caseId))
      .orderBy(asc(adaInteractiveLogTable.createdAt));

    const accommodations = await db
      .select()
      .from(approvedAccommodationsTable)
      .where(and(eq(approvedAccommodationsTable.caseId, caseId), eq(approvedAccommodationsTable.isActive, true)));

    res.json({ case: adaCase, log, accommodations });
  } catch (err) {
    logger.error({ err }, "ADA case fetch error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// POST /api/ada/cases  (employee portal submission — public)
router.post("/ada/cases", async (req: Request, res: Response) => {
  try {
    const {
      employeeNumber,
      employeeFirstName,
      employeeLastName,
      employeeEmail,
      disabilityDescription,
      functionalLimitations,
      accommodationRequested,
      isTemporary,
      estimatedDuration,
      hasPhysicianSupport,
      additionalNotes,
      submittedBy,
    } = req.body as Record<string, unknown>;

    // Resolve org — accept from query param (?org=slug) or request body (orgSlug)
    const orgSlug = (req.query["org"] as string | undefined)
      ?? ((req.body as Record<string, unknown>).orgSlug as string | undefined);

    let organizationId: string | null = null;
    if (orgSlug) {
      const [org] = await db.select({ id: organizationsTable.id }).from(organizationsTable).where(eq(organizationsTable.slug, orgSlug)).limit(1);
      organizationId = org?.id ?? null;
    }
    if (!organizationId) { res.status(400).json({ error: "Organization not found" }); return; }

    const caseNumber = generateCaseNumber();
    const accessToken = require("node:crypto").randomBytes(32).toString("hex");

    const [adaCase] = await db.insert(adaCasesTable).values({
      organizationId,
      caseNumber,
      employeeNumber: String(employeeNumber ?? ""),
      employeeFirstName: employeeFirstName as string | undefined,
      employeeLastName: employeeLastName as string | undefined,
      employeeEmail: employeeEmail as string | undefined,
      disabilityDescription: disabilityDescription as string | undefined,
      functionalLimitations: functionalLimitations as string | undefined,
      accommodationRequested: accommodationRequested as string | undefined,
      isTemporary: Boolean(isTemporary),
      estimatedDuration: estimatedDuration as string | undefined,
      hasPhysicianSupport: hasPhysicianSupport as boolean | undefined,
      additionalNotes: additionalNotes as string | undefined,
      submittedBy: submittedBy as string | undefined,
      status: "pending_review",
      displayStatus: "Pending HR Review",
      accessToken,
    }).returning();

    // Log the submission
    await db.insert(adaInteractiveLogTable).values({
      caseId: adaCase.id,
      entryType: "employee_response",
      authorName: (submittedBy as string) ?? "Employee",
      authorRole: "employee",
      content: `Accommodation request submitted via employee portal.\n\nFunctional Limitations: ${functionalLimitations ?? "Not specified"}\n\nAccommodation Requested: ${accommodationRequested ?? "Not specified"}`,
    });

    // Send acknowledgment email to employee if email provided
    if (employeeEmail && typeof employeeEmail === "string" && employeeEmail.trim()) {
      const employeeName = [employeeFirstName, employeeLastName].filter(Boolean).join(" ") || "Employee";
      try {
        await sendNoticeEmail({
          to: employeeEmail.trim(),
          subject: `Your Accommodation Request Has Been Received — Case ${caseNumber}`,
          noticeType: "ADA_ACKNOWLEDGMENT",
          content: `Dear ${employeeName},

Thank you for submitting your accommodation request. We have received your request and assigned it case number ${caseNumber}.

What happens next:
• An HR representative will review your request and initiate the interactive accommodation process
• We may reach out to gather additional information or to schedule a meeting
• You may be asked to provide supporting documentation from your healthcare provider

You can check the status of your request by visiting your employee portal. If you have any immediate questions, please contact HR directly.

Case Number: ${caseNumber}
Submitted: ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}

This is an automated notification. Please do not reply to this email.`,
        });
      } catch {
        // Non-fatal — log but don't fail the request
        logger.warn({ caseId: adaCase.id }, "Failed to send ADA acknowledgment email");
      }
    }

    res.status(201).json({ caseNumber, id: adaCase.id, accessToken });
  } catch (err) {
    logger.error({ err }, "ADA case create error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// PATCH /api/ada/cases/:caseId  (HR — update status, decision, etc.)
router.patch("/ada/cases/:caseId", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  const { caseId } = req.params;
  try {
    const [existing] = await db.select().from(adaCasesTable)
      .where(and(eq(adaCasesTable.id, caseId), eq(adaCasesTable.organizationId, authed.user.organizationId))).limit(1);
    if (!existing) { res.status(404).json({ error: "Case not found" }); return; }

    const allowed = ["status", "displayStatus", "decision", "decisionDate", "decisionNotes", "hardshipJustification", "assignedToUserId", "physicianCertSentAt", "physicianCertReceivedAt", "employeeEmail"];
    const updates: Record<string, unknown> = { updatedAt: new Date() };
    for (const key of allowed) {
      if (key in req.body) updates[key] = req.body[key];
    }

    const [updated] = await db.update(adaCasesTable).set(updates).where(eq(adaCasesTable.id, caseId)).returning();
    res.json(updated);
  } catch (err) {
    logger.error({ err }, "ADA case update error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── Interactive Process Log ──────────────────────────────────────────────────

// POST /api/ada/cases/:caseId/log  (add a manual log entry — HR or system)
router.post("/ada/cases/:caseId/log", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  const { caseId } = req.params;
  const { entryType, content } = req.body as { entryType?: string; content?: string };

  if (!entryType || !content?.trim()) {
    res.status(400).json({ error: "entryType and content are required" });
    return;
  }

  try {
    const [adaCase] = await db.select({ id: adaCasesTable.id })
      .from(adaCasesTable)
      .where(and(eq(adaCasesTable.id, caseId), eq(adaCasesTable.organizationId, authed.user.organizationId)))
      .limit(1);
    if (!adaCase) { res.status(404).json({ error: "Case not found" }); return; }

    const [entry] = await db.insert(adaInteractiveLogTable).values({
      caseId,
      entryType,
      authorId: authed.user.sub,
      authorName: [authed.user.firstName, authed.user.lastName].filter(Boolean).join(" ") || authed.user.email,
      authorRole: "hr",
      content: content.trim(),
    }).returning();

    res.status(201).json(entry);
  } catch (err) {
    logger.error({ err }, "ADA log entry error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── Ada Agent Conversation ───────────────────────────────────────────────────

// POST /api/ada/cases/:caseId/agent
router.post("/ada/cases/:caseId/agent", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  const { caseId } = req.params;
  const { message, history, lookupJan } = req.body as {
    message?: string;
    history?: AdaMessage[];
    lookupJan?: boolean;
  };

  if (!message?.trim()) { res.status(400).json({ error: "message is required" }); return; }

  try {
    const [adaCase] = await db.select().from(adaCasesTable)
      .where(and(eq(adaCasesTable.id, caseId), eq(adaCasesTable.organizationId, authed.user.organizationId)))
      .limit(1);
    if (!adaCase) { res.status(404).json({ error: "Case not found" }); return; }

    const result = await runAdaTurn({
      caseData: adaCase,
      conversationHistory: history ?? [],
      userMessage: message.trim(),
      userRole: authed.user.role ?? "hr_user",
      userName: [authed.user.firstName, authed.user.lastName].filter(Boolean).join(" ") || authed.user.email,
      lookupJan,
    });

    // Log the Ada interaction to the interactive process log
    await db.insert(adaInteractiveLogTable).values([
      {
        caseId,
        entryType: "hr_note",
        authorId: authed.user.sub,
        authorName: [authed.user.firstName, authed.user.lastName].filter(Boolean).join(" ") || authed.user.email,
        authorRole: "hr",
        content: message.trim(),
      },
      {
        caseId,
        entryType: "ada_determination",
        authorName: "Ada (ADA Agent)",
        authorRole: "system",
        content: result.response,
        metadata: result.janLookupPerformed ? JSON.stringify({ janLookup: true }) : undefined,
      },
    ]);

    res.json(result);
  } catch (err) {
    logger.error({ err }, "Ada agent error");
    res.status(500).json({ error: "Failed to get Ada response" });
  }
});

// ── Physician Certification ──────────────────────────────────────────────────

// GET /api/ada/cases/:caseId/physician-cert  (generate letter preview)
router.get("/ada/cases/:caseId/physician-cert", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  const { caseId } = req.params;
  try {
    const [adaCase] = await db.select().from(adaCasesTable)
      .where(and(eq(adaCasesTable.id, caseId), eq(adaCasesTable.organizationId, authed.user.organizationId)))
      .limit(1);
    if (!adaCase) { res.status(404).json({ error: "Case not found" }); return; }
    const letter = await generatePhysicianCertRequest(adaCase);
    res.json({ letter });
  } catch (err) {
    logger.error({ err }, "ADA physician cert preview error");
    res.status(500).json({ error: "Failed to generate physician certification" });
  }
});

// POST /api/ada/cases/:caseId/physician-cert  (generate + send)
router.post("/ada/cases/:caseId/physician-cert", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  const { caseId } = req.params;
  // Accept certContent from frontend (pre-generated preview) to avoid a redundant AI call.
  // employeeEmail is the recipient — frontend sends it as "employeeEmail".
  const { employeeEmail, certContent: providedContent } = req.body as {
    employeeEmail?: string;
    certContent?: string;
  };

  try {
    const [adaCase] = await db.select().from(adaCasesTable)
      .where(and(eq(adaCasesTable.id, caseId), eq(adaCasesTable.organizationId, authed.user.organizationId)))
      .limit(1);
    if (!adaCase) { res.status(404).json({ error: "Case not found" }); return; }

    // Re-use the letter the user already previewed; only regenerate if not provided
    const certContent = providedContent?.trim() || await generatePhysicianCertRequest(adaCase);

    // Build portal return instructions (appended to cert before PDF generation)
    const appUrl = getAppUrl();
    const portalUrl = adaCase.accessToken
      ? `${appUrl}/leaveiq/portal?token=${adaCase.accessToken}`
      : null;
    const returnInstructions = [
      "",
      "─────────────────────────────────────────────────────────────────────",
      "HOW TO RETURN THIS COMPLETED FORM",
      "─────────────────────────────────────────────────────────────────────",
      "",
      "Once completed, please return this form using ONE of the following methods:",
      "",
      portalUrl
        ? `1. EMPLOYEE PORTAL (preferred): The employee can upload this completed form at:\n   ${portalUrl}\n   After visiting the portal, select "Upload Document" and choose "Medical Certification" as the document type.`
        : "1. EMPLOYEE PORTAL: Ask the employee for their portal link to upload this completed form directly.",
      "",
      `2. EMAIL: Return to HR at the contact information provided on this letter.`,
      "",
      `3. FAX/MAIL: Contact HR for mailing or fax details.`,
      "",
      `Case Reference: ${adaCase.caseNumber}`,
      `Please return within 15 business days of the date of this request.`,
    ].join("\n");

    const certWithInstructions = certContent + returnInstructions;

    // Generate PDF using pure Node.js (same approach as FMLA med cert)
    const { buildAdaCertPdf } = await import("../lib/adaPdfBuilder.js").catch(() => ({ buildAdaCertPdf: null }));
    let pdfBuffer: Buffer | null = null;
    if (buildAdaCertPdf) {
      try { pdfBuffer = buildAdaCertPdf(certWithInstructions); } catch { /* fall through to text-only */ }
    }
    // Fallback: build PDF inline using the same algorithm as buildMedCertPdf
    if (!pdfBuffer) {
      pdfBuffer = buildSimplePdf(certWithInstructions);
    }
    const pdfBase64 = pdfBuffer.toString("base64");

    // Send email — use the explicit recipient address, fall back to case email
    const recipientEmail = employeeEmail?.trim() || adaCase.employeeEmail;
    let emailSent = false;
    let emailError: string | undefined;
    if (recipientEmail) {
      try {
        emailSent = await sendNoticeEmail({
          to: recipientEmail,
          content: `Please find the ADA Physician Certification Request attached as a PDF.\n\nCase Number: ${adaCase.caseNumber}\n\nPlease complete the attached form and return it within 15 business days.`,
          caseNumber: adaCase.caseNumber,
          employeeNumber: adaCase.employeeNumber ?? "",
          noticeType: "ADA_PHYSICIAN_CERT",
          attachments: [
            {
              filename: `ADA_Physician_Cert_${adaCase.caseNumber ?? "request"}.pdf`,
              content: pdfBase64,
            },
          ],
        });
        if (!emailSent) {
          emailError = "Email delivery is not configured (RESEND_API_KEY missing). The certification has been recorded.";
        }
      } catch (emailErr) {
        // Email delivery failure is logged but non-fatal — cert is still recorded in the case
        logger.error({ emailErr }, "ADA physician cert email delivery failed — recording cert anyway");
        emailError = emailErr instanceof Error ? emailErr.message : "Email delivery failed";
      }
    } else {
      emailError = "No email address on file for this employee. The certification has been recorded.";
    }

    // Mark cert as sent; use "awaiting_physician" so the UI status badge renders correctly
    await db.update(adaCasesTable).set({
      physicianCertSentAt: new Date(),
      status: "awaiting_physician",
      displayStatus: "Awaiting Physician Cert",
      updatedAt: new Date(),
    }).where(eq(adaCasesTable.id, caseId));

    // Log it
    await db.insert(adaInteractiveLogTable).values({
      caseId,
      entryType: "physician_cert_sent",
      authorId: authed.user.sub,
      authorName: [authed.user.firstName, authed.user.lastName].filter(Boolean).join(" ") || authed.user.email,
      authorRole: "hr",
      content: `ADA Physician Certification form sent to ${recipientEmail ?? "employee"} on ${new Date().toLocaleDateString()}.`,
      metadata: JSON.stringify({ certContent }),
    });

    res.json({ ok: true, certContent, emailSent, emailError });
  } catch (err) {
    logger.error({ err }, "ADA physician cert error");
    res.status(500).json({ error: "Failed to send physician certification" });
  }
});

// ── Approval / Denial Letters ────────────────────────────────────────────────

// POST /api/ada/cases/:caseId/approval-letter
router.post("/ada/cases/:caseId/approval-letter", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  const { caseId } = req.params;
  const { accommodations } = req.body as { accommodations?: string[] };

  if (!Array.isArray(accommodations) || accommodations.length === 0) {
    res.status(400).json({ error: "accommodations array required" });
    return;
  }

  try {
    const [adaCase] = await db.select().from(adaCasesTable)
      .where(and(eq(adaCasesTable.id, caseId), eq(adaCasesTable.organizationId, authed.user.organizationId)))
      .limit(1);
    if (!adaCase) { res.status(404).json({ error: "Case not found" }); return; }

    const letter = await generateApprovalLetter(adaCase, accommodations, [authed.user.firstName, authed.user.lastName].filter(Boolean).join(" ") || authed.user.email);
    res.json({ letter });
  } catch (err) {
    logger.error({ err }, "ADA approval letter error");
    res.status(500).json({ error: "Failed to generate letter" });
  }
});

// POST /api/ada/cases/:caseId/denial-letter
router.post("/ada/cases/:caseId/denial-letter", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  const { caseId } = req.params;
  const { hardshipJustification } = req.body as { hardshipJustification?: string };

  if (!hardshipJustification?.trim()) {
    res.status(400).json({ error: "hardshipJustification required" });
    return;
  }

  try {
    const [adaCase] = await db.select().from(adaCasesTable)
      .where(and(eq(adaCasesTable.id, caseId), eq(adaCasesTable.organizationId, authed.user.organizationId)))
      .limit(1);
    if (!adaCase) { res.status(404).json({ error: "Case not found" }); return; }

    const letter = await generateDenialLetter(adaCase, hardshipJustification, [authed.user.firstName, authed.user.lastName].filter(Boolean).join(" ") || authed.user.email);
    res.json({ letter });
  } catch (err) {
    logger.error({ err }, "ADA denial letter error");
    res.status(500).json({ error: "Failed to generate letter" });
  }
});

// ── Accommodations ────────────────────────────────────────────────────────────

// POST /api/ada/cases/:caseId/accommodations  (record approved accommodations)
router.post("/ada/cases/:caseId/accommodations", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  const { caseId } = req.params;
  const { description, category, startDate, endDate, isOngoing } = req.body as Record<string, unknown>;

  try {
    const [adaCase] = await db.select().from(adaCasesTable)
      .where(and(eq(adaCasesTable.id, caseId), eq(adaCasesTable.organizationId, authed.user.organizationId)))
      .limit(1);
    if (!adaCase) { res.status(404).json({ error: "Case not found" }); return; }

    const employeeName = [adaCase.employeeFirstName, adaCase.employeeLastName].filter(Boolean).join(" ") || `Employee #${adaCase.employeeNumber}`;
    const calendarLabel = `${employeeName} — Reasonable Accommodation`;

    const [accommodation] = await db.insert(approvedAccommodationsTable).values({
      caseId,
      organizationId: authed.user.organizationId!,
      description: String(description),
      category: category as string | undefined,
      startDate: startDate as string | undefined,
      endDate: endDate as string | undefined,
      isOngoing: isOngoing !== false,
      calendarLabel,
    }).returning();

    // Log it
    await db.insert(adaInteractiveLogTable).values({
      caseId,
      entryType: "accommodation_approved",
      authorId: authed.user.sub,
      authorName: [authed.user.firstName, authed.user.lastName].filter(Boolean).join(" ") || authed.user.email,
      authorRole: "hr",
      content: `Accommodation approved: ${description}${isOngoing ? " (ongoing)" : startDate ? ` effective ${startDate}` : ""}`,
    });

    res.status(201).json(accommodation);
  } catch (err) {
    logger.error({ err }, "ADA accommodation record error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// GET /api/ada/accommodations/calendar — for calendar display (legacy)
router.get("/ada/accommodations/calendar", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  try {
    const accommodations = await db
      .select()
      .from(approvedAccommodationsTable)
      .where(and(
        eq(approvedAccommodationsTable.organizationId, authed.user.organizationId),
        eq(approvedAccommodationsTable.isActive, true),
      ));
    res.json({ accommodations });
  } catch (err) {
    logger.error({ err }, "ADA calendar accommodations error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// GET /api/ada/calendar — enriched calendar data with caseNumber
router.get("/ada/calendar", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  try {
    const rows = await db
      .select({
        id: approvedAccommodationsTable.id,
        caseId: approvedAccommodationsTable.caseId,
        description: approvedAccommodationsTable.description,
        category: approvedAccommodationsTable.category,
        startDate: approvedAccommodationsTable.startDate,
        endDate: approvedAccommodationsTable.endDate,
        isOngoing: approvedAccommodationsTable.isOngoing,
        calendarLabel: approvedAccommodationsTable.calendarLabel,
        isActive: approvedAccommodationsTable.isActive,
        caseNumber: adaCasesTable.caseNumber,
      })
      .from(approvedAccommodationsTable)
      .leftJoin(adaCasesTable, eq(approvedAccommodationsTable.caseId, adaCasesTable.id))
      .where(and(
        eq(approvedAccommodationsTable.organizationId, authed.user.organizationId!),
        eq(approvedAccommodationsTable.isActive, true),
      ));
    res.json({ accommodations: rows });
  } catch (err) {
    logger.error({ err }, "ADA calendar error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── Calendar Invites ─────────────────────────────────────────────────────────

// POST /api/ada/cases/:caseId/calendar-invite
router.post("/ada/cases/:caseId/calendar-invite", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  const { caseId } = req.params;
  const { title, description, scheduledAt, durationMinutes, attendeeEmails } = req.body as Record<string, unknown>;

  if (!title || !scheduledAt || !Array.isArray(attendeeEmails)) {
    res.status(400).json({ error: "title, scheduledAt, and attendeeEmails required" });
    return;
  }

  try {
    const [adaCase] = await db.select().from(adaCasesTable)
      .where(and(eq(adaCasesTable.id, caseId), eq(adaCasesTable.organizationId, authed.user.organizationId)))
      .limit(1);
    if (!adaCase) { res.status(404).json({ error: "Case not found" }); return; }

    const hrEmail = authed.user.email;
    const allAttendees = [...new Set([...attendeeEmails as string[], hrEmail])];

    const icsContent = generateIcs({
      title: String(title),
      description: description ? String(description) : `ADA Interactive Process — Case ${adaCase.caseNumber}`,
      startDate: new Date(scheduledAt as string),
      durationMinutes: durationMinutes ? Number(durationMinutes) : 30,
      organizerEmail: hrEmail,
      organizerName: [authed.user.firstName, authed.user.lastName].filter(Boolean).join(" ") || hrEmail,
      attendeeEmails: allAttendees,
    });

    // Store the invite record
    const [invite] = await db.insert(calendarInvitesTable).values({
      organizationId: authed.user.organizationId,
      caseType: "ada",
      caseId,
      caseNumber: adaCase.caseNumber,
      title: String(title),
      description: description ? String(description) : undefined,
      scheduledAt: new Date(scheduledAt as string),
      durationMinutes: durationMinutes ? String(durationMinutes) : "30",
      attendeeEmails: allAttendees.join(","),
      organizerEmail: hrEmail,
      icsGenerated: true,
    }).returning();

    // Send the .ics via email to all attendees
    for (const email of allAttendees) {
      try {
        await sendNoticeEmail({
          to: email,
          content: `You have been invited to:\n\n${title}\nDate: ${new Date(scheduledAt as string).toLocaleString()}\nDuration: ${durationMinutes ?? 30} minutes\n\nCase: ${adaCase.caseNumber}\n\n${description ?? ""}\n\nPlease open the attached .ics file to add this event to your calendar.`,
          caseNumber: adaCase.caseNumber,
          employeeNumber: adaCase.employeeNumber ?? "",
          noticeType: "CALENDAR_INVITE",
          attachments: [{ filename: "invite.ics", content: Buffer.from(icsContent).toString("base64") }],
        });
      } catch { /* best-effort */ }
    }

    await db.update(calendarInvitesTable).set({ sentAt: new Date() }).where(eq(calendarInvitesTable.id, invite.id));

    // Log to interactive process
    await db.insert(adaInteractiveLogTable).values({
      caseId,
      entryType: "follow_up_scheduled",
      authorId: authed.user.sub,
      authorName: [authed.user.firstName, authed.user.lastName].filter(Boolean).join(" ") || authed.user.email,
      authorRole: "hr",
      content: `Follow-up meeting scheduled: "${title}" on ${new Date(scheduledAt as string).toLocaleString()}. Invites sent to: ${allAttendees.join(", ")}`,
    });

    res.json({ ok: true, invite, icsContent });
  } catch (err) {
    logger.error({ err }, "ADA calendar invite error");
    res.status(500).json({ error: "Failed to create calendar invite" });
  }
});

// ── Leave Knowledge Admin (sys admin only) ───────────────────────────────────

// POST /api/ada/scrape-leave-laws  (trigger manual scrape — sys admin)
router.post("/ada/scrape-leave-laws", requireAuth, async (req: Request, res: Response) => {
  const authed = req as AuthenticatedRequest;
  if (authed.user.role !== "system_admin" && authed.user.role !== "hr_admin") {
    res.status(403).json({ error: "Forbidden" }); return;
  }
  try {
    // Run async — respond immediately
    import("../lib/leaveKnowledgeScraper.js").then(({ runDailyScrape }) => {
      runDailyScrape().catch((err) => logger.error({ err }, "Manual leave law scrape error"));
    });
    res.json({ ok: true, message: "Scrape started in background" });
  } catch (err) {
    res.status(500).json({ error: "Failed to start scrape" });
  }
});

export default router;
