/**
 * PerformIQ Native E-Signature Routes
 *
 * POST   /api/performiq/cases/:caseId/signatures/request   — HR sends doc to employee
 * GET    /api/performiq/cases/:caseId/signatures           — get signature record (HR)
 * GET    /api/piq/sign?token=xxx                           — employee views doc (public)
 * POST   /api/piq/sign                                     — employee signs or declines (public)
 * POST   /api/performiq/cases/:caseId/signatures/manager-sign — manager signs (HR)
 * GET    /api/performiq/cases/:caseId/signatures/download-pdf — download PDF (HR)
 */
import { Router, type Request, type Response } from "express";
import { eq, and, desc } from "drizzle-orm";
import {
  db,
  piqCasesTable,
  piqSignaturesTable,
  piqDocumentsTable,
  piqDocumentTypesTable,
  employeesTable,
  organizationsTable,
} from "@workspace/db";
import { requirePiqAuth, type PiqAuthenticatedRequest } from "../../lib/piqJwtAuth.js";
import { getAppUrl, sendNoticeEmail } from "../../lib/email.js";
import { logger } from "../../lib/logger.js";
import crypto from "node:crypto";

const router = Router();

// ── PDF generation for PerformIQ documents ────────────────────────────────────

function buildDocumentPdf(
  content: string,
  title: string,
  employeeName: string,
  employeeSignature: string | null,
  employeeSignedAt: Date | null,
  managerSignature: string | null,
  managerSignedAt: Date | null,
): Buffer {
  const PW = 612, PH = 792, MX = 50, MY = 50;
  const CW = PW - MX * 2;

  function esc(s: string): string {
    return s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
  }
  function approxW(text: string, size: number): number {
    return text.length * size * 0.52;
  }
  function wordWrap(text: string, size: number, maxW: number): string[] {
    if (approxW(text, size) <= maxW) return [text];
    const words = text.split(" ");
    const lines: string[] = [];
    let cur = "";
    for (const w of words) {
      const next = cur ? cur + " " + w : w;
      if (approxW(next, size) <= maxW) { cur = next; }
      else { if (cur) lines.push(cur); cur = w; }
    }
    if (cur) lines.push(cur);
    return lines.length ? lines : [text];
  }

  interface Row { text: string; bold: boolean; sz: number; x: number; lineH: number; }
  const rows: Row[] = [];

  function addRow(text: string, bold: boolean, sz: number, indent = 0, extra = 0) {
    rows.push({ text, bold, sz, x: MX + indent, lineH: sz + 4 + extra });
  }

  // Header
  addRow(title.toUpperCase(), true, 14, 0, 6);
  addRow(`Employee: ${employeeName}`, false, 10, 0, 4);
  addRow(`Generated by Leavara PerformIQ  -  Confidential`, false, 9, 0, 10);
  addRow("─".repeat(80), false, 8, 0, 6);

  // Document body
  for (const raw of content.split("\n")) {
    const trimmed = raw.trim();
    if (!trimmed) { addRow("", false, 10, 0, 2); continue; }
    const isSectionHeader = /^[A-Z][A-Z\s\-]{4,}:?\s*$/.test(trimmed) || /^\d+\.\s+[A-Z]/.test(trimmed);
    const isIndented = raw.startsWith("  ") || raw.startsWith("\t");
    const indent = isIndented ? 20 : 0;
    if (isSectionHeader) {
      addRow("", false, 4, 0, 0);
      for (const wl of wordWrap(trimmed, 10, CW)) addRow(wl, true, 10, 0, 0);
    } else {
      for (const wl of wordWrap(trimmed, 10, CW - indent)) addRow(wl, false, 10, indent, 0);
    }
  }

  // Signature block
  addRow("", false, 12, 0, 0);
  addRow("─".repeat(80), false, 8, 0, 6);
  addRow("SIGNATURES", true, 11, 0, 6);

  if (employeeSignature && employeeSignedAt) {
    addRow(`Employee Signature:  ${employeeSignature}`, false, 10, 0, 2);
    addRow(`Signed:  ${employeeSignedAt.toLocaleString("en-US", { dateStyle: "long", timeStyle: "short" })}`, false, 9, 0, 4);
  } else {
    addRow("Employee Signature:  [ Not yet signed ]", false, 10, 0, 4);
  }

  if (managerSignature && managerSignedAt) {
    addRow(`Manager/HR Signature:  ${managerSignature}`, false, 10, 0, 2);
    addRow(`Signed:  ${managerSignedAt.toLocaleString("en-US", { dateStyle: "long", timeStyle: "short" })}`, false, 9, 0, 4);
  } else {
    addRow("Manager/HR Signature:  [ Not yet signed ]", false, 10, 0, 4);
  }

  addRow("", false, 6, 0, 0);
  addRow("Digitally signed via Leavara PerformIQ", false, 8, 0, 0);

  // --- Paginate rows ---
  const startY = PH - MY - 18;
  const pages: { row: Row; y: number }[][] = [];
  let curPage: { row: Row; y: number }[] = [];
  let y = startY;
  for (const row of rows) {
    if (y - row.sz < MY + 20 && curPage.length > 0) { pages.push(curPage); curPage = []; y = startY; }
    if (row.text) curPage.push({ row, y });
    y -= row.lineH;
  }
  if (curPage.length > 0 || pages.length === 0) pages.push(curPage);

  // --- Build PDF content streams ---
  const streams = pages.map((pg) => {
    const cmds: string[] = ["BT"];
    let curFont = "", curSz = 0;
    for (const { row, y: ry } of pg) {
      const fn = row.bold ? "/F2" : "/F1";
      if (fn !== curFont || row.sz !== curSz) { cmds.push(`${fn} ${row.sz} Tf`); curFont = fn; curSz = row.sz; }
      cmds.push(`1 0 0 1 ${row.x} ${ry.toFixed(1)} Tm`);
      cmds.push(`(${esc(row.text)}) Tj`);
    }
    cmds.push("ET");
    return cmds.join("\n");
  });

  const nPages = pages.length;
  const firstPageObj = 3;
  const fontNrm = firstPageObj + nPages;
  const fontBld = fontNrm + 1;
  const firstStream = fontBld + 1;
  const totalObjs = firstStream + nPages;

  const parts: string[] = [];
  const offsets: number[] = new Array(totalObjs).fill(0);
  let pos = 0;
  function w(s: string) { parts.push(s); pos += Buffer.byteLength(s, "latin1"); }

  w("%PDF-1.4\n%\xe2\xe3\xcf\xd3\n");
  offsets[1] = pos;
  w(`1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n`);
  const kids = Array.from({ length: nPages }, (_, i) => `${firstPageObj + i} 0 R`).join(" ");
  offsets[2] = pos;
  w(`2 0 obj\n<< /Type /Pages /Kids [${kids}] /Count ${nPages} >>\nendobj\n`);
  for (let i = 0; i < nPages; i++) {
    offsets[firstPageObj + i] = pos;
    w(`${firstPageObj + i} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PW} ${PH}] /Contents ${firstStream + i} 0 R /Resources << /Font << /F1 ${fontNrm} 0 R /F2 ${fontBld} 0 R >> >> >>\nendobj\n`);
  }
  offsets[fontNrm] = pos;
  w(`${fontNrm} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj\n`);
  offsets[fontBld] = pos;
  w(`${fontBld} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>\nendobj\n`);
  for (let i = 0; i < nPages; i++) {
    const stream = streams[i];
    const len = Buffer.byteLength(stream, "latin1");
    offsets[firstStream + i] = pos;
    w(`${firstStream + i} 0 obj\n<< /Length ${len} >>\nstream\n${stream}\nendstream\nendobj\n`);
  }
  const xrefPos = pos;
  w(`xref\n0 ${totalObjs}\n`);
  w(`0000000000 65535 f \n`);
  for (let i = 1; i < totalObjs; i++) w(`${String(offsets[i]).padStart(10, "0")} 00000 n \n`);
  w(`trailer\n<< /Size ${totalObjs} /Root 1 0 R >>\nstartxref\n${xrefPos}\n%%EOF\n`);
  return Buffer.from(parts.join(""), "latin1");
}

// ── Helper: format document for text representation ──────────────────────────

function documentContentToText(content: Record<string, unknown>, docTypeLabel: string): string {
  const sections: [string, string][] = [
    ["Document Purpose", content.documentTypePurpose as string],
    ["Incident Description", content.incidentDescription as string],
    ["Policy Violations", content.policyViolations as string],
    ["Impact & Consequences", content.impactConsequences as string],
    ["Prior Discipline History", content.priorDisciplineHistory as string],
    ["Expectations Going Forward", content.expectationsGoingForward as string],
    ["Consequences of Non-Compliance", content.failureConsequences as string],
    ["Additional Notes", content.additionalNotes as string],
  ];

  const lines: string[] = [
    docTypeLabel.toUpperCase(),
    "",
  ];

  for (const [label, val] of sections) {
    if (val?.trim()) {
      lines.push(`${label.toUpperCase()}`, val.trim(), "");
    }
  }
  return lines.join("\n");
}

// ── Routes ────────────────────────────────────────────────────────────────────

// POST /api/performiq/cases/:caseId/signatures/request
router.post(
  "/performiq/cases/:caseId/signatures/request",
  requirePiqAuth,
  async (req: Request, res: Response): Promise<void> => {
    const authed = req as PiqAuthenticatedRequest;
    const { caseId } = req.params;

    try {
      // Load case + employee + document
      const [caseRow] = await db
        .select()
        .from(piqCasesTable)
        .where(and(eq(piqCasesTable.id, caseId), eq(piqCasesTable.organizationId, authed.piqUser.organizationId!)))
        .limit(1);
      if (!caseRow) { res.status(404).json({ error: "Case not found" }); return; }

      const [employee] = await db.select().from(employeesTable).where(eq(employeesTable.id, caseRow.employeeId)).limit(1);
      if (!employee) { res.status(404).json({ error: "Employee not found" }); return; }

      const employeeEmail = employee.workEmail ?? employee.personalEmail;
      if (!employeeEmail) { res.status(400).json({ error: "Employee has no email on file" }); return; }

      // Load latest document
      const [doc] = await db
        .select()
        .from(piqDocumentsTable)
        .where(eq(piqDocumentsTable.caseId, caseId))
        .orderBy(desc(piqDocumentsTable.version))
        .limit(1);

      // Load document type label
      const [docType] = caseRow.documentTypeId
        ? await db.select({ displayLabel: piqDocumentTypesTable.displayLabel }).from(piqDocumentTypesTable).where(eq(piqDocumentTypesTable.id, caseRow.documentTypeId)).limit(1)
        : [null];
      const docLabel = docType?.displayLabel ?? "Performance Document";

      // Generate employee access token
      const employeeAccessToken = crypto.randomBytes(32).toString("hex");
      const signUrl = `${getAppUrl()}/performiq/sign?token=${employeeAccessToken}`;

      // Create (or replace) signature record
      await db.delete(piqSignaturesTable).where(
        and(eq(piqSignaturesTable.caseId, caseId), eq(piqSignaturesTable.provider, "native")),
      );

      const [sig] = await db.insert(piqSignaturesTable).values({
        caseId,
        organizationId: authed.piqUser.organizationId!,
        employeeId: employee.id,
        method: "esignature",
        provider: "native",
        status: "sent",
        deliveredBy: authed.piqUser.sub,
        deliveryDate: new Date(),
        employeeAccessToken,
      }).returning();
      try {
        await sendNoticeEmail({
          to: employeeEmail,
          subject: `Action Required: Review and Sign — ${docLabel}`,
          noticeType: "PIQ_ESIGNATURE_REQUEST",
          content: `Dear ${employee.fullName},

A ${docLabel} has been prepared for your review and signature.

Please review the document and provide your electronic signature by clicking the link below:

${signUrl}

This link is unique to you. Please do not share it.

If you have questions about this document, please contact HR.

Case: ${caseRow.caseNumber}
Document: ${docLabel}`,
        });
      } catch (emailErr) {
        logger.warn({ emailErr, caseId }, "Failed to send e-signature email");
      }

      res.json({ ok: true, signatureId: sig.id, employeeEmail });
    } catch (err) {
      logger.error({ err, caseId }, "signature request error");
      res.status(500).json({ error: "Internal server error" });
    }
  },
);

// GET /api/performiq/cases/:caseId/signatures
router.get(
  "/performiq/cases/:caseId/signatures",
  requirePiqAuth,
  async (req: Request, res: Response): Promise<void> => {
    const authed = req as PiqAuthenticatedRequest;
    const { caseId } = req.params;
    try {
      const [sig] = await db
        .select()
        .from(piqSignaturesTable)
        .where(and(eq(piqSignaturesTable.caseId, caseId), eq(piqSignaturesTable.provider, "native")))
        .limit(1);
      res.json(sig ?? null);
    } catch (err) {
      logger.error({ err }, "get signature error");
      res.status(500).json({ error: "Internal server error" });
    }
  },
);

// GET /api/piq/sign?token=xxx  — public, no auth
router.get("/piq/sign", async (req: Request, res: Response): Promise<void> => {
  const token = req.query["token"] as string | undefined;
  if (!token) { res.status(400).json({ error: "token required" }); return; }

  try {
    const [sig] = await db
      .select()
      .from(piqSignaturesTable)
      .where(eq(piqSignaturesTable.employeeAccessToken, token))
      .limit(1);

    if (!sig) { res.status(404).json({ error: "Invalid or expired link" }); return; }
    if (sig.status === "declined") { res.json({ status: "declined", employeeComment: sig.employeeComment }); return; }
    if (sig.status === "completed" || sig.status === "employee_signed" || sig.status === "manager_signed") {
      res.json({ status: sig.status, alreadySigned: true }); return;
    }

    // Load case and document
    const [caseRow] = await db.select().from(piqCasesTable).where(eq(piqCasesTable.id, sig.caseId)).limit(1);
    const [employee] = await db.select().from(employeesTable).where(eq(employeesTable.id, sig.employeeId)).limit(1);
    const [doc] = await db
      .select()
      .from(piqDocumentsTable)
      .where(eq(piqDocumentsTable.caseId, sig.caseId))
      .orderBy(piqDocumentsTable.version)
      .limit(1);

    const [org] = await db
      .select({ name: organizationsTable.name })
      .from(organizationsTable)
      .where(eq(organizationsTable.id, sig.organizationId))
      .limit(1);

    const docLabel = (doc as any)?.documentTypeLabel ?? "Performance Document";
    const content = (doc as any)?.content;
    const docText = content ? documentContentToText(content, docLabel) : "";

    // Mark as viewed
    if (sig.status === "sent") {
      await db.update(piqSignaturesTable).set({ status: "viewed", updatedAt: new Date() }).where(eq(piqSignaturesTable.id, sig.id));
    }

    res.json({
      status: "ok",
      caseNumber: caseRow?.caseNumber,
      employeeName: employee?.fullName,
      organizationName: org?.name,
      docLabel,
      docText,
      signatureId: sig.id,
    });
  } catch (err) {
    logger.error({ err }, "get sign page error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// POST /api/piq/sign  — public, no auth
router.post("/piq/sign", async (req: Request, res: Response): Promise<void> => {
  const { token, action, signatureData, comment } = req.body as {
    token?: string;
    action?: "sign" | "decline";
    signatureData?: string;
    comment?: string;
  };

  if (!token || !action) { res.status(400).json({ error: "token and action required" }); return; }

  try {
    const [sig] = await db
      .select()
      .from(piqSignaturesTable)
      .where(eq(piqSignaturesTable.employeeAccessToken, token))
      .limit(1);

    if (!sig) { res.status(404).json({ error: "Invalid or expired link" }); return; }
    if (sig.status !== "sent" && sig.status !== "viewed") {
      res.status(409).json({ error: "Document has already been actioned" }); return;
    }

    if (action === "decline") {
      await db.update(piqSignaturesTable).set({
        status: "declined",
        employeeComment: comment?.trim() || null,
        updatedAt: new Date(),
      }).where(eq(piqSignaturesTable.id, sig.id));

      // Update case status back to manager_revision
      await db.update(piqCasesTable).set({ status: "manager_revision", updatedAt: new Date() })
        .where(eq(piqCasesTable.id, sig.caseId));

      res.json({ ok: true, status: "declined" });
      return;
    }

    if (action === "sign") {
      if (!signatureData?.trim()) { res.status(400).json({ error: "signatureData required" }); return; }

      await db.update(piqSignaturesTable).set({
        status: "employee_signed",
        employeeSignatureData: signatureData.trim(),
        employeeSignedAt: new Date(),
        updatedAt: new Date(),
      }).where(eq(piqSignaturesTable.id, sig.id));

      res.json({ ok: true, status: "employee_signed" });
      return;
    }

    res.status(400).json({ error: "action must be sign or decline" });
  } catch (err) {
    logger.error({ err }, "post sign error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// POST /api/performiq/cases/:caseId/signatures/manager-sign
router.post(
  "/performiq/cases/:caseId/signatures/manager-sign",
  requirePiqAuth,
  async (req: Request, res: Response): Promise<void> => {
    const authed = req as PiqAuthenticatedRequest;
    const { caseId } = req.params;
    const { signatureData } = req.body as { signatureData?: string };

    if (!signatureData?.trim()) { res.status(400).json({ error: "signatureData required" }); return; }

    try {
      const [sig] = await db
        .select()
        .from(piqSignaturesTable)
        .where(and(
          eq(piqSignaturesTable.caseId, caseId),
          eq(piqSignaturesTable.provider, "native"),
          eq(piqSignaturesTable.organizationId, authed.piqUser.organizationId!),
        ))
        .limit(1);

      if (!sig) { res.status(404).json({ error: "Signature record not found" }); return; }
      if (sig.status !== "employee_signed") {
        res.status(409).json({ error: `Employee must sign first (current status: ${sig.status})` }); return;
      }

      // Load case and document for PDF generation
      const [caseRow] = await db.select().from(piqCasesTable).where(eq(piqCasesTable.id, caseId)).limit(1);
      const [employee] = await db.select().from(employeesTable).where(eq(employeesTable.id, sig.employeeId)).limit(1);
      const [doc] = await db
        .select()
        .from(piqDocumentsTable)
        .where(eq(piqDocumentsTable.caseId, caseId))
        .orderBy(desc(piqDocumentsTable.version))
        .limit(1);

      const docLabel = (doc as any)?.documentTypeLabel ?? "Performance Document";
      const content = (doc as any)?.content;
      const docText = content ? documentContentToText(content, docLabel) : "";
      const managerSignedAt = new Date();

      // Generate final signed PDF
      const pdfBuffer = buildDocumentPdf(
        docText,
        docLabel,
        employee?.fullName ?? "Employee",
        sig.employeeSignatureData,
        sig.employeeSignedAt ? new Date(sig.employeeSignedAt) : null,
        signatureData.trim(),
        managerSignedAt,
      );
      const pdfBase64 = pdfBuffer.toString("base64");

      // Update signature record
      await db.update(piqSignaturesTable).set({
        status: "completed",
        managerSignatureData: signatureData.trim(),
        managerSignedAt,
        signedAt: managerSignedAt,
        signedPdfContent: pdfBase64,
        updatedAt: new Date(),
      }).where(eq(piqSignaturesTable.id, sig.id));

      // Close the case
      await db.update(piqCasesTable).set({
        status: "closed",
        updatedAt: new Date(),
      }).where(eq(piqCasesTable.id, caseId));

      logger.info({ caseId, caseNumber: caseRow?.caseNumber }, "PerformIQ case signed and closed");

      res.json({ ok: true, status: "completed" });
    } catch (err) {
      logger.error({ err, caseId }, "manager sign error");
      res.status(500).json({ error: "Internal server error" });
    }
  },
);

// GET /api/performiq/cases/:caseId/signatures/download-pdf
router.get(
  "/performiq/cases/:caseId/signatures/download-pdf",
  requirePiqAuth,
  async (req: Request, res: Response): Promise<void> => {
    const authed = req as PiqAuthenticatedRequest;
    const { caseId } = req.params;

    try {
      const [sig] = await db
        .select()
        .from(piqSignaturesTable)
        .where(and(
          eq(piqSignaturesTable.caseId, caseId),
          eq(piqSignaturesTable.provider, "native"),
          eq(piqSignaturesTable.organizationId, authed.piqUser.organizationId!),
        ))
        .limit(1);

      if (!sig || !sig.signedPdfContent) {
        res.status(404).json({ error: "Signed PDF not available yet" }); return;
      }

      const [caseRow] = await db.select({ caseNumber: piqCasesTable.caseNumber }).from(piqCasesTable).where(eq(piqCasesTable.id, caseId)).limit(1);
      const pdfBuffer = Buffer.from(sig.signedPdfContent, "base64");
      const filename = `${caseRow?.caseNumber ?? caseId}_signed.pdf`;

      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
      res.send(pdfBuffer);
    } catch (err) {
      logger.error({ err }, "download signed pdf error");
      res.status(500).json({ error: "Internal server error" });
    }
  },
);

export default router;
